version: '3'
services:
  database:
    image: "postgres:13"
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - employee-data:/var/lib/postgersql/data

volumes:
  employee-data:
